/*
 * generated by Xtext
 */
package br.poli.ecomp.compiladores.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NotCUiModule extends br.poli.ecomp.compiladores.ui.AbstractNotCUiModule {
	public NotCUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
