/**
 * generated by Xtext
 */
package br.poli.ecomp.compiladores.validation;

import br.poli.ecomp.compiladores.validation.AbstractNotCValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class NotCValidator extends AbstractNotCValidator {
}
