/*
* generated by Xtext
*/
package br.poli.ecomp.compiladores.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class NotCAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("br/poli/ecomp/compiladores/parser/antlr/internal/InternalNotC.tokens");
	}
}
