/**
 * generated by Xtext
 */
package br.poli.ecomp.compiladores.generator;

import br.poli.ecomp.compiladores.notC.Code;
import br.poli.ecomp.compiladores.notC.Declaration;
import br.poli.ecomp.compiladores.notC.Expr5;
import br.poli.ecomp.compiladores.notC.Expression;
import br.poli.ecomp.compiladores.notC.Function;
import br.poli.ecomp.compiladores.notC.IDDeclaration;
import br.poli.ecomp.compiladores.notC.RDeclaration;
import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class NotCGenerator implements IGenerator {
  public CharSequence compileCode(final Code code) {
    StringConcatenation _builder = new StringConcatenation();
    {
      EList<Declaration> _declarations = code.getDeclarations();
      boolean _notEquals = (!Objects.equal(_declarations, null));
      if (_notEquals) {
        {
          EList<Declaration> _declarations_1 = code.getDeclarations();
          for(final Declaration declaration : _declarations_1) {
            CharSequence _compile = this.compile(declaration);
            _builder.append(_compile, "");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    {
      EList<Function> _functions = code.getFunctions();
      boolean _notEquals_1 = (!Objects.equal(_functions, null));
      if (_notEquals_1) {
        {
          EList<Function> _functions_1 = code.getFunctions();
          for(final Function function : _functions_1) {
            _builder.append("function.compile");
          }
        }
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _compile(final Declaration declaration) {
    StringConcatenation _builder = new StringConcatenation();
    String _type = declaration.getType();
    _builder.append(_type, "");
    _builder.append(" ");
    RDeclaration _value = declaration.getValue();
    Object _compile = this.compile(_value);
    _builder.append(_compile, "");
    _builder.append(";");
    return _builder;
  }
  
  protected CharSequence _compile(final RDeclaration rDeclaration) {
    StringConcatenation _builder = new StringConcatenation();
    {
      IDDeclaration _id = rDeclaration.getId();
      boolean _notEquals = (!Objects.equal(_id, null));
      if (_notEquals) {
        IDDeclaration _id_1 = rDeclaration.getId();
        Object _compile = this.compile(_id_1);
        _builder.append(_compile, "");
      }
    }
    {
      RDeclaration _left = rDeclaration.getLeft();
      boolean _notEquals_1 = (!Objects.equal(_left, null));
      if (_notEquals_1) {
        RDeclaration _left_1 = rDeclaration.getLeft();
        Object _compile_1 = this.compile(_left_1);
        _builder.append(_compile_1, "");
      }
    }
    {
      RDeclaration _next = rDeclaration.getNext();
      boolean _notEquals_2 = (!Objects.equal(_next, null));
      if (_notEquals_2) {
        _builder.append(", ");
        RDeclaration _next_1 = rDeclaration.getNext();
        Object _compile_2 = this.compile(_next_1);
        _builder.append(_compile_2, "");
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final IDDeclaration idDeclaration) {
    StringConcatenation _builder = new StringConcatenation();
    String _id = idDeclaration.getId();
    _builder.append(_id, "");
    {
      Expression _value = idDeclaration.getValue();
      boolean _notEquals = (!Objects.equal(_value, null));
      if (_notEquals) {
        _builder.append(" = ");
        Expression _value_1 = idDeclaration.getValue();
        Object _compile = this.compile(_value_1);
        _builder.append(_compile, "");
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final Expression expr) {
    StringConcatenation _builder = new StringConcatenation();
    {
      Expr5 _result = expr.getResult();
      boolean _notEquals = (!Objects.equal(_result, null));
      if (_notEquals) {
        Expr5 _result_1 = expr.getResult();
        Object _compile = this.compile(_result_1);
        _builder.append(_compile, "");
      }
    }
    {
      Expression _value = expr.getValue();
      boolean _notEquals_1 = (!Objects.equal(_value, null));
      if (_notEquals_1) {
        _builder.append("( ");
        Expression _value_1 = expr.getValue();
        Object _compile_1 = this.compile(_value_1);
        _builder.append(_compile_1, "");
        _builder.append(" )");
      }
    }
    {
      Expression _left = expr.getLeft();
      boolean _notEquals_2 = (!Objects.equal(_left, null));
      if (_notEquals_2) {
        Expression _left_1 = expr.getLeft();
        Object _compile_2 = this.compile(_left_1);
        _builder.append(_compile_2, "");
      }
    }
    {
      String _operator = expr.getOperator();
      boolean _notEquals_3 = (!Objects.equal(_operator, null));
      if (_notEquals_3) {
        _builder.append(" ");
        String _operator_1 = expr.getOperator();
        _builder.append(_operator_1, "");
        _builder.append(" ");
      }
    }
    {
      Expression _right = expr.getRight();
      boolean _notEquals_4 = (!Objects.equal(_right, null));
      if (_notEquals_4) {
        Expression _right_1 = expr.getRight();
        Object _compile_3 = this.compile(_right_1);
        _builder.append(_compile_3, "");
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final Expr5 expr) {
    StringConcatenation _builder = new StringConcatenation();
    int _value = expr.getValue();
    _builder.append(_value, "");
    return _builder;
  }
  
  protected CharSequence _compile(final Function function) {
    StringConcatenation _builder = new StringConcatenation();
    return _builder;
  }
  
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Code> _filter = Iterables.<Code>filter(_iterable, Code.class);
    for (final Code e : _filter) {
      URI _normalizedURI = EcoreUtil2.getNormalizedURI(resource);
      String _lastSegment = _normalizedURI.lastSegment();
      CharSequence _compileCode = this.compileCode(e);
      fsa.generateFile(_lastSegment, _compileCode);
    }
  }
  
  public CharSequence compile(final EObject declaration) {
    if (declaration instanceof Declaration) {
      return _compile((Declaration)declaration);
    } else if (declaration instanceof Expr5) {
      return _compile((Expr5)declaration);
    } else if (declaration instanceof Expression) {
      return _compile((Expression)declaration);
    } else if (declaration instanceof Function) {
      return _compile((Function)declaration);
    } else if (declaration instanceof IDDeclaration) {
      return _compile((IDDeclaration)declaration);
    } else if (declaration instanceof RDeclaration) {
      return _compile((RDeclaration)declaration);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(declaration).toString());
    }
  }
}
