/**
 * generated by Xtext
 */
package br.poli.ecomp.compiladores.generator;

import br.poli.ecomp.compiladores.notC.Block;
import br.poli.ecomp.compiladores.notC.Code;
import br.poli.ecomp.compiladores.notC.Command;
import br.poli.ecomp.compiladores.notC.Declaration;
import br.poli.ecomp.compiladores.notC.Expression;
import br.poli.ecomp.compiladores.notC.FuncParam;
import br.poli.ecomp.compiladores.notC.Function;
import br.poli.ecomp.compiladores.notC.IDDeclaration;
import br.poli.ecomp.compiladores.notC.IfCommand;
import br.poli.ecomp.compiladores.notC.RDeclaration;
import br.poli.ecomp.compiladores.notC.Statement;
import br.poli.ecomp.compiladores.notC.Type;
import br.poli.ecomp.compiladores.notC.WhileCommand;
import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class NotCGenerator implements IGenerator {
  public CharSequence compileCode(final Code code) {
    StringConcatenation _builder = new StringConcatenation();
    {
      EList<Declaration> _declarations = code.getDeclarations();
      boolean _notEquals = (!Objects.equal(_declarations, null));
      if (_notEquals) {
        {
          EList<Declaration> _declarations_1 = code.getDeclarations();
          for(final Declaration declaration : _declarations_1) {
            CharSequence _compile = this.compile(declaration);
            _builder.append(_compile, "");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    {
      EList<Function> _functions = code.getFunctions();
      boolean _notEquals_1 = (!Objects.equal(_functions, null));
      if (_notEquals_1) {
        {
          EList<Function> _functions_1 = code.getFunctions();
          for(final Function function : _functions_1) {
            CharSequence _compile_1 = this.compile(function);
            _builder.append(_compile_1, "");
          }
        }
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _compile(final Declaration declaration) {
    StringConcatenation _builder = new StringConcatenation();
    Type _type = declaration.getType();
    Object _compile = this.compile(_type);
    _builder.append(_compile, "");
    _builder.append(" ");
    RDeclaration _value = declaration.getValue();
    Object _compile_1 = this.compile(_value);
    _builder.append(_compile_1, "");
    _builder.append(";");
    return _builder;
  }
  
  protected CharSequence _compile(final RDeclaration rDeclaration) {
    StringConcatenation _builder = new StringConcatenation();
    {
      IDDeclaration _id = rDeclaration.getId();
      boolean _notEquals = (!Objects.equal(_id, null));
      if (_notEquals) {
        IDDeclaration _id_1 = rDeclaration.getId();
        Object _compile = this.compile(_id_1);
        _builder.append(_compile, "");
      }
    }
    {
      RDeclaration _left = rDeclaration.getLeft();
      boolean _notEquals_1 = (!Objects.equal(_left, null));
      if (_notEquals_1) {
        RDeclaration _left_1 = rDeclaration.getLeft();
        Object _compile_1 = this.compile(_left_1);
        _builder.append(_compile_1, "");
      }
    }
    {
      RDeclaration _next = rDeclaration.getNext();
      boolean _notEquals_2 = (!Objects.equal(_next, null));
      if (_notEquals_2) {
        _builder.append(", ");
        RDeclaration _next_1 = rDeclaration.getNext();
        Object _compile_2 = this.compile(_next_1);
        _builder.append(_compile_2, "");
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final IDDeclaration idDeclaration) {
    StringConcatenation _builder = new StringConcatenation();
    String _id = idDeclaration.getId();
    _builder.append(_id, "");
    {
      Expression _value = idDeclaration.getValue();
      boolean _notEquals = (!Objects.equal(_value, null));
      if (_notEquals) {
        _builder.append(" = ");
        Expression _value_1 = idDeclaration.getValue();
        Object _compile = this.compile(_value_1);
        _builder.append(_compile, "");
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final Expression expr) {
    StringConcatenation _builder = new StringConcatenation();
    {
      Expression _value = expr.getValue();
      boolean _notEquals = (!Objects.equal(_value, null));
      if (_notEquals) {
        _builder.append("( ");
        Expression _value_1 = expr.getValue();
        _builder.append(_value_1, "");
        _builder.append(" )");
      }
    }
    {
      Expression _left = expr.getLeft();
      boolean _notEquals_1 = (!Objects.equal(_left, null));
      if (_notEquals_1) {
        Expression _left_1 = expr.getLeft();
        Object _compile_1 = this.compile(_left_1);
        _builder.append(_compile_1, "");
      }
    }
    {
      String _operator = expr.getOperator();
      boolean _notEquals_2 = (!Objects.equal(_operator, null));
      if (_notEquals_2) {
        _builder.append(" ");
        String _operator_1 = expr.getOperator();
        _builder.append(_operator_1, "");
        _builder.append(" ");
      }
    }
    {
      Expression _right = expr.getRight();
      boolean _notEquals_3 = (!Objects.equal(_right, null));
      if (_notEquals_3) {
        Expression _right_1 = expr.getRight();
        Object _compile_2 = this.compile(_right_1);
        _builder.append(_compile_2, "");
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final Function function) {
    StringConcatenation _builder = new StringConcatenation();
    Type _type = function.getType();
    Object _compile = this.compile(_type);
    _builder.append(_compile, "");
    _builder.append(" ");
    String _id = function.getId();
    _builder.append(_id, "");
    _builder.append(" ( ");
    {
      FuncParam _param = function.getParam();
      boolean _notEquals = (!Objects.equal(_param, null));
      if (_notEquals) {
        FuncParam _param_1 = function.getParam();
        Object _compile_1 = this.compile(_param_1);
        _builder.append(_compile_1, "");
      }
    }
    _builder.append(")");
    _builder.newLineIfNotEmpty();
    Block _block = function.getBlock();
    Object _compile_2 = this.compile(_block);
    _builder.append(_compile_2, "");
    return _builder;
  }
  
  protected CharSequence _compile(final FuncParam funcParam) {
    StringConcatenation _builder = new StringConcatenation();
    Type _type = funcParam.getType();
    Object _compile = this.compile(_type);
    _builder.append(_compile, "");
    _builder.append(" ");
    String _id = funcParam.getId();
    _builder.append(_id, "");
    {
      FuncParam _next = funcParam.getNext();
      boolean _notEquals = (!Objects.equal(_next, null));
      if (_notEquals) {
        _builder.append(", ");
        FuncParam _next_1 = funcParam.getNext();
        Object _compile_1 = this.compile(_next_1);
        _builder.append(_compile_1, "");
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final Block block) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("{");
    _builder.newLine();
    {
      Statement _statement = block.getStatement();
      boolean _notEquals = (!Objects.equal(_statement, null));
      if (_notEquals) {
        Statement _statement_1 = block.getStatement();
        Object _compile = this.compile(_statement_1);
        _builder.append(_compile, "");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    return _builder;
  }
  
  protected CharSequence _compile(final Statement statement) {
    StringConcatenation _builder = new StringConcatenation();
    {
      EList<Declaration> _declarations = statement.getDeclarations();
      boolean _notEquals = (!Objects.equal(_declarations, null));
      if (_notEquals) {
        {
          EList<Declaration> _declarations_1 = statement.getDeclarations();
          for(final Declaration declaration : _declarations_1) {
            _builder.append("\t");
            Object _compile = this.compile(declaration);
            _builder.append(_compile, "");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    {
      EList<Command> _commands = statement.getCommands();
      boolean _notEquals_1 = (!Objects.equal(_commands, null));
      if (_notEquals_1) {
        {
          EList<Command> _commands_1 = statement.getCommands();
          for(final Command command : _commands_1) {
            _builder.append("\t");
            Object _compile_1 = this.compile(command);
            _builder.append(_compile_1, "");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final IfCommand ifcommand) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("if ( ");
    Expression _expr = ifcommand.getExpr();
    Object _compile = this.compile(_expr);
    _builder.append(_compile, "");
    _builder.append(" ) ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    Block _ifBlock = ifcommand.getIfBlock();
    Object _compile_1 = this.compile(_ifBlock);
    _builder.append(_compile_1, "\t");
    {
      Block _elseBlock = ifcommand.getElseBlock();
      boolean _notEquals = (!Objects.equal(_elseBlock, null));
      if (_notEquals) {
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("else ");
        _builder.newLine();
        _builder.append("\t");
        Block _elseBlock_1 = ifcommand.getElseBlock();
        Object _compile_2 = this.compile(_elseBlock_1);
        _builder.append(_compile_2, "\t");
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final WhileCommand whileCommand) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("while ( ");
    Expression _expr = whileCommand.getExpr();
    Object _compile = this.compile(_expr);
    _builder.append(_compile, "");
    _builder.append(" )");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    Block _whileBlock = whileCommand.getWhileBlock();
    Object _compile_1 = this.compile(_whileBlock);
    _builder.append(_compile_1, "\t");
    {
      Block _whileBlock_1 = whileCommand.getWhileBlock();
      boolean _notEquals = (!Objects.equal(_whileBlock_1, null));
      if (_notEquals) {
      }
    }
    return _builder;
  }
  
  protected CharSequence _compile(final Type type) {
    StringConcatenation _builder = new StringConcatenation();
    String _value = type.getValue();
    _builder.append(_value, "");
    return _builder;
  }
  
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Code> _filter = Iterables.<Code>filter(_iterable, Code.class);
    for (final Code e : _filter) {
      URI _normalizedURI = EcoreUtil2.getNormalizedURI(resource);
      String _lastSegment = _normalizedURI.lastSegment();
      CharSequence _compileCode = this.compileCode(e);
      fsa.generateFile(_lastSegment, _compileCode);
    }
  }
  
  public CharSequence compile(final EObject ifcommand) {
    if (ifcommand instanceof IfCommand) {
      return _compile((IfCommand)ifcommand);
    } else if (ifcommand instanceof WhileCommand) {
      return _compile((WhileCommand)ifcommand);
    } else if (ifcommand instanceof Block) {
      return _compile((Block)ifcommand);
    } else if (ifcommand instanceof Declaration) {
      return _compile((Declaration)ifcommand);
    } else if (ifcommand instanceof Expression) {
      return _compile((Expression)ifcommand);
    } else if (ifcommand instanceof FuncParam) {
      return _compile((FuncParam)ifcommand);
    } else if (ifcommand instanceof Function) {
      return _compile((Function)ifcommand);
    } else if (ifcommand instanceof IDDeclaration) {
      return _compile((IDDeclaration)ifcommand);
    } else if (ifcommand instanceof RDeclaration) {
      return _compile((RDeclaration)ifcommand);
    } else if (ifcommand instanceof Statement) {
      return _compile((Statement)ifcommand);
    } else if (ifcommand instanceof Type) {
      return _compile((Type)ifcommand);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(ifcommand).toString());
    }
  }
}
