/*
 * generated by Xtext
 */
package br.poli.ecomp.compiladores.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractNotCValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(br.poli.ecomp.compiladores.notC.NotCPackage.eINSTANCE);
		return result;
	}
}
