/*
* generated by Xtext
*/
package br.poli.ecomp.compiladores;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class NotCStandaloneSetup extends NotCStandaloneSetupGenerated{

	public static void doSetup() {
		new NotCStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

