/*
 * generated by Xtext
 */
package br.poli.ecomp.compiladores;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NotCRuntimeModule extends br.poli.ecomp.compiladores.AbstractNotCRuntimeModule {

}
