/*
 * generated by Xtext
 */
package br.poli.ecomp.compiladores.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import br.poli.ecomp.compiladores.ui.internal.NotCActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NotCExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return NotCActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return NotCActivator.getInstance().getInjector(NotCActivator.BR_POLI_ECOMP_COMPILADORES_NOTC);
	}
	
}
