/*
* generated by Xtext
*/
package br.poli.ecomp.compiladores;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class NotCUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return br.poli.ecomp.compiladores.ui.internal.NotCActivator.getInstance().getInjector("br.poli.ecomp.compiladores.NotC");
	}
	
}
